### PR TITLE
chore: define garden version in a variable

### PR DESCRIPTION
**Pull request by vvagaytsev**
To avoid repetition and to make version upgrades easier.

### CODE REVIEW

**Comment by vvagaytsev** [comment]
A few more thoughts here:

**1. Configurable version.** We can put the version in a `.env` file and always source it when the script starts.

**2. Reinstallable Garden (optional).** We can allow to overwrite the existing Garden if the explicitly defined version is passed and if it's different from the currently installed one.

**3. Automatically version update.** If we have a `.env` file, we can create a GH action that will create a PR with the version update on every Core release.

@worldofgeese @ShankyJS wdyt?

**Comment by worldofgeese** [comment]
Question: why not always use latest?

**Comment by vvagaytsev** [comment]
> Question: why not always use latest?

Well, we can use the `edge-bonsai` tag. But sometimes the edge version may be broken. The latest stable would be better.

**Comment by vvagaytsev** [comment]
Ah, we can use `latest` release, of course

**Review by worldofgeese — APPROVED** [review]

**Comment by vvagaytsev** [comment]
Closing this because `start.sh` script was deleted in #29.

**Pull request closed without merging**
