### PR TITLE
Use latest `garden` always

### PR DESCRIPTION
**Pull request by worldofgeese**
This fixes the timeout issue in Cloud Shell.

### CODE REVIEW

**Review by ShankyJS — APPROVED** [review]

**Comment by vvagaytsev** [comment]
I think this will stop working as soon as we release 0.13.8. The latest release label changes on each 0.13.x release. So we still need to specify an explicit version.

**Review by vvagaytsev — CHANGES_REQUESTED** [review]
See the comment above. We can
1) Create a GitHub action in the Core repo that will create a PR with the version update on each Core release
2) Write a simple script that will call the API and parse the response from https://api.github.com/repos/garden-io/garden/releases/latest

**Comment by worldofgeese** [comment]
@vvagaytsev good catch! I've committed a fix that should always parse the latest tarball from GitHub's API. I've tested this in Cloud Shell and can confirm it's sourcing the right object. Can you review?

**Review by vvagaytsev — APPROVED** [review]
Thanks, @worldofgeese 👍 
Looks great and well automated 🌞

**Pull request merged**
